Repository UMC-7th-Ttt/Ttt_BE, pull requests merged in 2025-01, with the labels that each got.

#2 [feat #1] 엔티티 클래스 추가
  build.gradle
  src/main/java/com/umc/ttt/TttApplication.java
  src/main/java/com/umc/ttt/domain/book/entity/Book.java
  src/main/java/com/umc/ttt/domain/book/entity/BookScrap.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/BookClub.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/BookClubMember.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/Comment.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/ReadingRecord.java
  src/main/java/com/umc/ttt/domain/bookLetter/entity/BookLetter.java
  src/main/java/com/umc/ttt/domain/member/entity/Member.java
  src/main/java/com/umc/ttt/domain/member/entity/enums/ProviderType.java
  src/main/java/com/umc/ttt/domain/member/entity/enums/Role.java
  src/main/java/com/umc/ttt/domain/place/entity/Place.java
  src/main/java/com/umc/ttt/domain/place/entity/PlaceScrap.java
  src/main/java/com/umc/ttt/domain/place/entity/enums/PlaceCategory.java
  src/main/java/com/umc/ttt/domain/review/entity/Review.java
  src/main/java/com/umc/ttt/global/common/BaseEntity.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#4 [feat #3] 알라딘 Open API 데이터 저장 API 구현
  src/main/java/com/umc/ttt/domain/book/controller/BookRestController.java
  src/main/java/com/umc/ttt/domain/book/converter/BookConverter.java
  src/main/java/com/umc/ttt/domain/book/dto/BookResponseDTO.java
  src/main/java/com/umc/ttt/domain/book/entity/Book.java
  src/main/java/com/umc/ttt/domain/book/repository/BookRepository.java
  src/main/java/com/umc/ttt/domain/book/service/BookCommandService.java
  src/main/java/com/umc/ttt/domain/book/service/BookCommandServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#8 [feat #6] 독립서점, 북카페 Open API 데이터 저장
  build.gradle
  src/main/java/com/umc/ttt/domain/place/controller/PlaceRestController.java
  src/main/java/com/umc/ttt/domain/place/entity/Place.java
  src/main/java/com/umc/ttt/domain/place/repository/PlaceRepository.java
  src/main/java/com/umc/ttt/domain/place/service/PlaceCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceCommandService.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/PlaceHandler.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#11 [fix #9] yml 파일 제거
  .gitignore
  src/main/resources/application.yml
Labels: :bug: bug

#19 [feat #12] 공간 큐레이션, 상세 조회 및 스크랩 api 구현
  src/main/java/com/umc/ttt/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/ttt/domain/place/controller/PlaceRestController.java
  src/main/java/com/umc/ttt/domain/place/converter/PlaceConverter.java
  src/main/java/com/umc/ttt/domain/place/dto/PlaceRequestDTO.java
  src/main/java/com/umc/ttt/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/umc/ttt/domain/place/entity/Place.java
  src/main/java/com/umc/ttt/domain/place/service/PlaceApiService.java
  src/main/java/com/umc/ttt/domain/place/service/PlaceCommandService.java
  src/main/java/com/umc/ttt/domain/place/service/PlaceQueryService.java
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceApiServiceImpl.java
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/scrap/controller/ScrapRestController.java
  src/main/java/com/umc/ttt/domain/scrap/converter/ScrapConverter.java
  src/main/java/com/umc/ttt/domain/scrap/dto/ScrapResponseDTO.java
  src/main/java/com/umc/ttt/domain/scrap/entity/BookScrap.java
  src/main/java/com/umc/ttt/domain/scrap/entity/PlaceScrap.java
  src/main/java/com/umc/ttt/domain/scrap/entity/ScrapFolder.java
  src/main/java/com/umc/ttt/domain/scrap/repository/BookScrapRepository.java
  src/main/java/com/umc/ttt/domain/scrap/repository/PlaceScrapRepository.java
  src/main/java/com/umc/ttt/domain/scrap/repository/ScrapFolderRepository.java
  src/main/java/com/umc/ttt/domain/scrap/service/ScrapCommandService.java
  src/main/java/com/umc/ttt/domain/scrap/service/ScrapQueryService.java
  src/main/java/com/umc/ttt/domain/scrap/service/impl/ScrapCommandCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/scrap/service/impl/ScrapQueryServiceImpl.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/MemberHandler.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/ScrapHandler.java
Labels: :sparkles: feature

#20 [Feat/#17] 북레터 작성/수정/삭제 API 구현
  src/main/java/com/umc/ttt/domain/bookLetter/Controller/BookLetterController.java
  src/main/java/com/umc/ttt/domain/bookLetter/Converter/BookLetterConverter.java
  src/main/java/com/umc/ttt/domain/bookLetter/bookLetterRepository/BookLetterRepository.java
  src/main/java/com/umc/ttt/domain/bookLetter/dto/BookLetterRequestDTO.java
  src/main/java/com/umc/ttt/domain/bookLetter/dto/BookLetterResponseDTO.java
  src/main/java/com/umc/ttt/domain/bookLetter/entity/BookLetter.java
  src/main/java/com/umc/ttt/domain/bookLetter/service/BookLetterCommandService.java
  src/main/java/com/umc/ttt/domain/bookLetter/service/BookLetterCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/BookHandler.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/BookLetterHandler.java
Labels: :sparkles: feature

#23 [feat #21] 북레터 리스트/상세페이지 조회 API구현
  src/main/java/com/umc/ttt/domain/bookLetter/Controller/BookLetterController.java
  src/main/java/com/umc/ttt/domain/bookLetter/Converter/BookLetterConverter.java
  src/main/java/com/umc/ttt/domain/bookLetter/dto/BookLetterResponseDTO.java
  src/main/java/com/umc/ttt/domain/bookLetter/service/BookLetterCommandService.java
  src/main/java/com/umc/ttt/domain/bookLetter/service/BookLetterCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookLetter/validation/annotataion/CheckPage.java
  src/main/java/com/umc/ttt/domain/bookLetter/validation/validator/CheckPageValidator.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#26 [refactor #24]책-북레터 다대다 변경
  src/main/java/com/umc/ttt/domain/bookLetter/Converter/BookLetterConverter.java
  src/main/java/com/umc/ttt/domain/bookLetter/bookLetterRepository/BookLetterBookRepository.java
  src/main/java/com/umc/ttt/domain/bookLetter/dto/BookLetterRequestDTO.java
  src/main/java/com/umc/ttt/domain/bookLetter/entity/BookLetter.java
  src/main/java/com/umc/ttt/domain/bookLetter/entity/BookLetterBook.java
  src/main/java/com/umc/ttt/domain/bookLetter/service/BookLetterCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookLetter/validation/annotataion/DuplicateBooks.java
  src/main/java/com/umc/ttt/domain/bookLetter/validation/validator/DuplicateBooksValidator.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
Labels: :recycle: refactor

#22 [feat #18] 책 검색 API 구현
  src/main/java/com/umc/ttt/domain/book/controller/BookRestController.java
  src/main/java/com/umc/ttt/domain/book/converter/BookConverter.java
  src/main/java/com/umc/ttt/domain/book/dto/BookFetchDTO.java
  src/main/java/com/umc/ttt/domain/book/dto/BookResponseDTO.java
  src/main/java/com/umc/ttt/domain/book/entity/BookCategory.java
  src/main/java/com/umc/ttt/domain/book/repository/BookRepository.java
  src/main/java/com/umc/ttt/domain/book/service/BookCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryService.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/member/entity/Member.java
  src/main/java/com/umc/ttt/domain/member/entity/MemberPreferedCategory.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/ttt/global/config/BookCategoryInitializer.java
Labels: :sparkles: feature

#27 [feat #12] 가까운 순/추천 순 공간 목록 조회
  src/main/java/com/umc/ttt/domain/place/controller/PlaceRestController.java
  src/main/java/com/umc/ttt/domain/place/converter/PlaceConverter.java
  src/main/java/com/umc/ttt/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/umc/ttt/domain/place/entity/Place.java
  src/main/java/com/umc/ttt/domain/place/repository/PlaceRepository.java
  src/main/java/com/umc/ttt/domain/place/service/PlaceQueryService.java
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/scrap/controller/ScrapRestController.java
  src/main/java/com/umc/ttt/domain/scrap/converter/ScrapConverter.java
  src/main/java/com/umc/ttt/domain/scrap/dto/ScrapResponseDTO.java
  src/main/java/com/umc/ttt/domain/scrap/repository/PlaceScrapRepository.java
  src/main/java/com/umc/ttt/domain/scrap/service/ScrapQueryService.java
  src/main/java/com/umc/ttt/domain/scrap/service/impl/ScrapQueryServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#29 [feat #28] 책 스크랩 API 구현
  src/main/java/com/umc/ttt/domain/scrap/controller/ScrapRestController.java
  src/main/java/com/umc/ttt/domain/scrap/converter/ScrapConverter.java
  src/main/java/com/umc/ttt/domain/scrap/dto/ScrapResponseDTO.java
  src/main/java/com/umc/ttt/domain/scrap/repository/BookScrapRepository.java
  src/main/java/com/umc/ttt/domain/scrap/service/ScrapCommandService.java
  src/main/java/com/umc/ttt/domain/scrap/service/impl/ScrapCommandCommandServiceImpl.java
Labels: :sparkles: feature

#31 [Feat/#30] 북클럽 개설/수정/삭제 API 구현
  src/main/java/com/umc/ttt/domain/bookClub/controller/BookClubController.java
  src/main/java/com/umc/ttt/domain/bookClub/converter/BookClubConvert.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/BookClubRequestDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/BookClubResponseDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/BookClub.java
  src/main/java/com/umc/ttt/domain/bookClub/handler/BookClubHandler.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/BookClubRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookLetter/entity/BookLetterBook.java
  src/main/java/com/umc/ttt/domain/bookLetter/handler/BookLetterBookHandler.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#33 [refactor #32] 스크랩 리팩토링
  src/main/java/com/umc/ttt/domain/scrap/controller/ScrapRestController.java
  src/main/java/com/umc/ttt/domain/scrap/converter/ScrapConverter.java
  src/main/java/com/umc/ttt/domain/scrap/dto/ScrapRequestDTO.java
  src/main/java/com/umc/ttt/domain/scrap/dto/ScrapResponseDTO.java
  src/main/java/com/umc/ttt/domain/scrap/entity/BookScrap.java
  src/main/java/com/umc/ttt/domain/scrap/entity/PlaceScrap.java
  src/main/java/com/umc/ttt/domain/scrap/repository/BookScrapRepository.java
  src/main/java/com/umc/ttt/domain/scrap/repository/PlaceScrapRepository.java
  src/main/java/com/umc/ttt/domain/scrap/service/ScrapCommandService.java
  src/main/java/com/umc/ttt/domain/scrap/service/ScrapQueryService.java
  src/main/java/com/umc/ttt/domain/scrap/service/impl/ScrapCommandCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/scrap/service/impl/ScrapQueryServiceImpl.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: feature, :recycle: refactor

#41 [feat #38] 나들이 북클럽 검색, 공간 추천 API 구현
  lombok.config
  src/main/java/com/umc/ttt/domain/book/converter/BookConverter.java
  src/main/java/com/umc/ttt/domain/book/service/BookCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookLetter/Converter/BookLetterConverter.java
  src/main/java/com/umc/ttt/domain/place/controller/PlaceRestController.java
  src/main/java/com/umc/ttt/domain/place/converter/PlaceConverter.java
  src/main/java/com/umc/ttt/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/umc/ttt/domain/place/repository/PlaceRepository.java
  src/main/java/com/umc/ttt/domain/place/service/PlaceQueryService.java
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/scrap/controller/ScrapRestController.java
  src/main/java/com/umc/ttt/domain/scrap/service/impl/ScrapCommandServiceImpl.java
Labels: :sparkles: feature

#39 [feat #35] 책마다 북클럽 상세 페이지 조회 API 구현
  src/main/java/com/umc/ttt/domain/book/converter/BookConverter.java
  src/main/java/com/umc/ttt/domain/book/repository/BookRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/controller/BookClubController.java
  src/main/java/com/umc/ttt/domain/bookClub/converter/BookClubConverter.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/BookClubResponseDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/BookClubMemberRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/ReadingRecordRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubServiceImpl.java
  src/main/java/com/umc/ttt/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#34 [feat #7] 회원가입/로그인 API 구현
  build.gradle
  src/main/java/com/umc/ttt/domain/member/controller/MemberController.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberLoginDTO.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberSignUpDTO.java
  src/main/java/com/umc/ttt/domain/member/entity/Member.java
  src/main/java/com/umc/ttt/domain/member/entity/enums/MemberStatus.java
  src/main/java/com/umc/ttt/domain/member/entity/enums/Role.java
  src/main/java/com/umc/ttt/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandService.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/config/SecurityConfig.java
  src/main/java/com/umc/ttt/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/umc/ttt/global/jwt/service/JwtService.java
  src/main/java/com/umc/ttt/global/jwt/util/PasswordUtil.java
  src/main/java/com/umc/ttt/global/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/umc/ttt/global/login/handler/LoginFailureHandler.java
  src/main/java/com/umc/ttt/global/login/handler/LoginSuccessHandler.java
  src/main/java/com/umc/ttt/global/login/service/LoginService.java
  src/main/java/com/umc/ttt/global/oauth2/CustomOAuth2User.java
  src/main/java/com/umc/ttt/global/oauth2/OAuthAttributes.java
  src/main/java/com/umc/ttt/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/umc/ttt/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/ttt/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/umc/ttt/global/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/umc/ttt/global/oauth2/userinfo/OAuth2UserInfo.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
Labels: :sparkles: feature

#46 Feat/#7
  build.gradle
  src/main/java/com/umc/ttt/domain/member/controller/MemberController.java
  src/main/java/com/umc/ttt/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberLoginDTO.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberSignUpDTO.java
  src/main/java/com/umc/ttt/domain/member/dto/TokenResponseDTO.java
  src/main/java/com/umc/ttt/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandService.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/JwtHandler.java
  src/main/java/com/umc/ttt/global/config/RedisConfig.java
  src/main/java/com/umc/ttt/global/config/SecurityConfig.java
  src/main/java/com/umc/ttt/global/jwt/entity/GeneratedToken.java
  src/main/java/com/umc/ttt/global/jwt/entity/RefreshToken.java
  src/main/java/com/umc/ttt/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/umc/ttt/global/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/umc/ttt/global/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/umc/ttt/global/jwt/service/JwtService.java
  src/main/java/com/umc/ttt/global/jwt/service/RefreshTokenService.java
  src/main/java/com/umc/ttt/global/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/umc/ttt/global/login/handler/LoginSuccessHandler.java
  src/main/java/com/umc/ttt/global/oauth2/OAuthAttributes.java
  src/main/java/com/umc/ttt/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/ttt/global/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/umc/ttt/global/oauth2/userinfo/OAuth2UserInfo.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#48 Update gradle.yml
  .github/workflows/gradle.yml
Labels: :bug: bug

#49 [feat #25] 책 상세 조회 API 구현
  .github/workflows/gradle.yml
  src/main/java/com/umc/ttt/domain/book/controller/BookRestController.java
  src/main/java/com/umc/ttt/domain/book/converter/BookConverter.java
  src/main/java/com/umc/ttt/domain/book/dto/BookResponseDTO.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryService.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryServiceImpl.java
  src/main/java/com/umc/ttt/global/config/CorsConfig.java
Labels: :sparkles: feature

#50 [chore] WebConfig 수정
  src/main/java/com/umc/ttt/global/config/WebConfig.java
Labels: :recycle: refactor

#55 Feat/#47
  build.gradle
  src/main/java/com/umc/ttt/domain/mail/controller/MailController.java
  src/main/java/com/umc/ttt/domain/mail/dto/MailRequestDTO.java
  src/main/java/com/umc/ttt/domain/mail/handler/EMailHandler.java
  src/main/java/com/umc/ttt/domain/mail/service/MailService.java
  src/main/java/com/umc/ttt/domain/mail/service/MailServiceImpl.java
  src/main/java/com/umc/ttt/domain/member/controller/MemberController.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberSignUpDTO.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandService.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/ttt/global/config/SecurityConfig.java
  src/main/java/com/umc/ttt/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/umc/ttt/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/umc/ttt/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/ttt/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/umc/ttt/global/redis/RedisService.java
Labels: :sparkles: feature

#59 [feat] CurrentMember 어노테이션으로 로그인한 멤버 정보 가져오기
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/place/controller/PlaceRestController.java
  src/main/java/com/umc/ttt/domain/scrap/controller/ScrapRestController.java
  src/main/java/com/umc/ttt/global/annotation/CurrentMember.java
  src/main/java/com/umc/ttt/global/annotation/CurrentMemberArgumentResolver.java
  src/main/java/com/umc/ttt/global/config/WebConfig.java
Labels: :sparkles: feature, :recycle: refactor

#60 [fix #58] google login idtoken api 구현
  build.gradle
  src/main/java/com/umc/ttt/domain/mail/controller/MailController.java
  src/main/java/com/umc/ttt/domain/member/controller/MemberController.java
  src/main/java/com/umc/ttt/global/config/SecurityConfig.java
  src/main/java/com/umc/ttt/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/umc/ttt/global/oauth2/service/GoogleIdTokenVerify.java
Labels: :recycle: refactor

#61 [feat #54] 책 에디터 픽 API 구현
  src/main/java/com/umc/ttt/domain/book/controller/BookRestController.java
  src/main/java/com/umc/ttt/domain/book/repository/BookRepository.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryService.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryServiceImpl.java
Labels: :sparkles: feature
