Repository UMC-7th-Ttt/Ttt_BE, pull requests merged in 2025-02, with the labels that each got.

#66 [feat #44] 서평 작성/수정 API 구현
  src/main/java/com/umc/ttt/domain/member/handler/MemberHandler.java
  src/main/java/com/umc/ttt/domain/review/controller/ReviewRestController.java
  src/main/java/com/umc/ttt/domain/review/converter/ReviewConverter.java
  src/main/java/com/umc/ttt/domain/review/dto/ReviewRequestDTO.java
  src/main/java/com/umc/ttt/domain/review/dto/ReviewResponseDTO.java
  src/main/java/com/umc/ttt/domain/review/entity/Review.java
  src/main/java/com/umc/ttt/domain/review/handler/ReviewHandler.java
  src/main/java/com/umc/ttt/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandService.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#67 [feat #64] 책마다 북클럽 서평 댓글/답글 api 구현
  src/main/java/com/umc/ttt/domain/bookClub/controller/CommentController.java
  src/main/java/com/umc/ttt/domain/bookClub/converter/CommentConverter.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/CommentRequestDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/CommentResponseDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/Comment.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/CommentRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookClub/service/CommentService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/CommentServiceImpl.java
  src/main/java/com/umc/ttt/domain/scrap/service/impl/ScrapCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#70 [feat #62] 책마다 북클럽 서평 인증하기 API 구현
  src/main/java/com/umc/ttt/domain/bookClub/controller/BookClubController.java
  src/main/java/com/umc/ttt/domain/bookClub/controller/ReadingRecordController.java
  src/main/java/com/umc/ttt/domain/bookClub/converter/ReadingRecordConverter.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/ReadingRecordRequestDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/ReadingRecordResponseDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/ReadingRecord.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/ReadingRecordRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookClub/service/ReadingRecordService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/ReadingRecordServiceImpl.java
  src/main/java/com/umc/ttt/global/config/BookCategoryInitializer.java
Labels: :sparkles: feature

#72 [feat #68] 서평 목록 보기(캘린더/모아보기) / 상세보기 API 구현
  src/main/java/com/umc/ttt/domain/review/controller/ReviewRestController.java
  src/main/java/com/umc/ttt/domain/review/converter/ReviewConverter.java
  src/main/java/com/umc/ttt/domain/review/dto/ReviewResponseDTO.java
  src/main/java/com/umc/ttt/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandService.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#76 [fix #75] 책마다 북클럽 상세 페이지 조회 예외 처리 수정
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryServiceImpl.java
Labels: :recycle: refactor

#78 [fix #77] 책 상세 조회 API 평점 및 서평 데이터 추가
  src/main/java/com/umc/ttt/domain/book/converter/BookConverter.java
  src/main/java/com/umc/ttt/domain/book/dto/BookResponseDTO.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/member/entity/Member.java
  src/main/java/com/umc/ttt/domain/review/repository/ReviewRepository.java
Labels: :recycle: refactor

#74 [fix #73] 로그인한 회원 정보로 변경
  src/main/java/com/umc/ttt/domain/book/controller/BookRestController.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryServiceImpl.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
Labels: :recycle: refactor

#81 [feat #69] 책마다 북클럽 서평 댓글/답글 좋아요 api 구현
  src/main/java/com/umc/ttt/domain/bookClub/controller/CommentController.java
  src/main/java/com/umc/ttt/domain/bookClub/converter/CommentConverter.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/CommentResponseDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/Comment.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/CommentLike.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/ReadingRecord.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/CommentLikeRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/service/CommentService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/CommentServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookLetter/entity/BookLetter.java
  src/main/java/com/umc/ttt/domain/member/entity/Member.java
  src/main/java/com/umc/ttt/domain/review/entity/Review.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#83 [refactor #82] 나들이 북클럽 리팩토링
  src/main/java/com/umc/ttt/domain/book/entity/Book.java
  src/main/java/com/umc/ttt/domain/member/repository/MemberPreferredCategoryRepository.java
  src/main/java/com/umc/ttt/domain/place/converter/PlaceConverter.java
  src/main/java/com/umc/ttt/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/umc/ttt/domain/place/entity/Place.java
  src/main/java/com/umc/ttt/domain/place/repository/PlaceRepository.java
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceApiServiceImpl.java
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandServiceImpl.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#86 [feat #71] 유저정보 저장 & 수정 & 로그아웃 권한 수정
  src/main/java/com/umc/ttt/domain/member/controller/MemberController.java
  src/main/java/com/umc/ttt/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberPassWordDTO.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberProfileDTO.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberSignUpDTO.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberUpdateInfoDTO.java
  src/main/java/com/umc/ttt/domain/member/entity/Member.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandService.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/config/SecurityConfig.java
  src/main/java/com/umc/ttt/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/umc/ttt/global/login/handler/LoginSuccessHandler.java
Labels: :sparkles: feature, :recycle: refactor

#84 [feat #79] 책 검색 결과 없을 경우 처리
  src/main/java/com/umc/ttt/domain/book/service/BookQueryServiceImpl.java
Labels: :sparkles: feature

#87 [fix #80] 책마다 북클럽 수정(최대 인원 수 -> 모집 현황)
  src/main/java/com/umc/ttt/domain/bookClub/controller/BookClubController.java
  src/main/java/com/umc/ttt/domain/bookClub/converter/BookClubConverter.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/BookClubRequestDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/BookClubResponseDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/entity/BookClub.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/BookClubMemberRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubServiceImpl.java
Labels: :recycle: refactor

#91 [feat] Kakao Geocoding API를 사용하여 위도, 경도를 주소로 변환
  src/main/java/com/umc/ttt/domain/place/controller/PlaceRestController.java
  src/main/java/com/umc/ttt/domain/place/converter/PlaceConverter.java
  src/main/java/com/umc/ttt/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/umc/ttt/domain/place/service/GeocodingService.java
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceApiServiceImpl.java
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceQueryServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#93 [fix #58] 구글 API 수정(ID_TOKEN 사용)
  src/main/java/com/umc/ttt/domain/member/controller/MemberController.java
  src/main/java/com/umc/ttt/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/umc/ttt/global/oauth2/service/GoogleIdTokenVerify.java
Labels: :recycle: refactor

#92 [feat #89] 홈 화면 조회 API 구현
  src/main/java/com/umc/ttt/domain/bookClub/repository/BookClubMemberRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookLetter/bookLetterRepository/BookLetterRepository.java
  src/main/java/com/umc/ttt/domain/bookLetter/entity/BookLetter.java
  src/main/java/com/umc/ttt/domain/bookLetter/entity/BookLetterCategory.java
  src/main/java/com/umc/ttt/domain/bookLetter/service/BookLetterCommandService.java
  src/main/java/com/umc/ttt/domain/bookLetter/service/BookLetterCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/member/repository/MemberPreferredCategoryRepository.java
  src/main/java/com/umc/ttt/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandService.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/com/umc/ttt/home/controller/HomeController.java
  src/main/java/com/umc/ttt/home/converter/HomeConverter.java
  src/main/java/com/umc/ttt/home/dto/HomeResponseDTO.java
  src/main/java/com/umc/ttt/home/service/HomeService.java
  src/main/java/com/umc/ttt/home/service/HomeServiceImpl.java
Labels: :sparkles: feature

#95 [feat #63] 베스트셀러 6권 조회 API 구현
  src/main/java/com/umc/ttt/domain/book/controller/BookRestController.java
  src/main/java/com/umc/ttt/domain/book/converter/BookConverter.java
  src/main/java/com/umc/ttt/domain/book/dto/BookFetchDTO.java
  src/main/java/com/umc/ttt/domain/book/dto/BookResponseDTO.java
  src/main/java/com/umc/ttt/domain/book/entity/Book.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryService.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryServiceImpl.java
Labels: :sparkles: feature

#94 [fix #56] 로그인한 회원정보로 변경
  build.gradle
  src/main/java/com/umc/ttt/domain/member/controller/MemberController.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/umc/ttt/domain/member/repository/MemberPreferredCategoryRepository.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandService.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/login/handler/LoginSuccessHandler.java
Labels: :recycle: refactor

#97 [feat #88] s3 설정 & 프로필 업로드 API 구현
  build.gradle
  src/main/java/com/umc/ttt/domain/member/controller/MemberController.java
  src/main/java/com/umc/ttt/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/ttt/domain/member/dto/MemberAddProfileDTO.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandService.java
  src/main/java/com/umc/ttt/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/aws/s3/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/umc/ttt/global/aws/s3/entity/Uuid.java
  src/main/java/com/umc/ttt/global/aws/s3/repository/UuidRepository.java
  src/main/java/com/umc/ttt/global/aws/s3/service/AmazonS3Manager.java
  src/main/java/com/umc/ttt/global/config/AmazonConfig.java
Labels: :sparkles: feature, :recycle: refactor

#102 [fix #99] 북레터 API 수정 (카테고리 구조 변경)
  src/main/java/com/umc/ttt/domain/bookLetter/Converter/BookLetterConverter.java
  src/main/java/com/umc/ttt/domain/bookLetter/bookLetterRepository/BookLetterCategoryRepository.java
  src/main/java/com/umc/ttt/domain/bookLetter/dto/BookLetterRequestDTO.java
  src/main/java/com/umc/ttt/domain/bookLetter/entity/BookLetter.java
  src/main/java/com/umc/ttt/domain/bookLetter/entity/BookLetterCategory.java
  src/main/java/com/umc/ttt/domain/bookLetter/handler/BookLetterCategoryHandler.java
  src/main/java/com/umc/ttt/domain/bookLetter/service/BookLetterCommandServiceImpl.java
Labels: :recycle: refactor

#105 [refactor #90] 책마다 북클럽 리팩토링
  src/main/java/com/umc/ttt/domain/book/converter/BookConverter.java
  src/main/java/com/umc/ttt/domain/book/dto/BookResponseDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/converter/BookClubConverter.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/BookClubResponseDTO.java
Labels: :recycle: refactor

#107 [feat #106] 책마다 북클럽 참여현황 api 구현
  src/main/java/com/umc/ttt/domain/bookClub/controller/BookClubController.java
  src/main/java/com/umc/ttt/domain/bookClub/converter/BookClubConverter.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/BookClubResponseDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/BookClubMemberRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/BookClubRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookClub/service/CommentServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookClub/service/ReadingRecordServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookLetter/controller/BookLetterController.java
  src/main/java/com/umc/ttt/domain/bookLetter/converter/BookLetterConverter.java
  src/main/java/com/umc/ttt/domain/bookLetter/repository/BookLetterBookRepository.java
  src/main/java/com/umc/ttt/domain/bookLetter/repository/BookLetterCategoryRepository.java
  src/main/java/com/umc/ttt/domain/bookLetter/repository/BookLetterRepository.java
  src/main/java/com/umc/ttt/domain/bookLetter/service/BookLetterCommandService.java
  src/main/java/com/umc/ttt/domain/bookLetter/service/BookLetterCommandServiceImpl.java
  src/main/java/com/umc/ttt/domain/home/controller/HomeController.java
  src/main/java/com/umc/ttt/domain/home/converter/HomeConverter.java
  src/main/java/com/umc/ttt/domain/home/dto/HomeResponseDTO.java
  src/main/java/com/umc/ttt/domain/home/service/HomeService.java
  src/main/java/com/umc/ttt/domain/home/service/HomeServiceImpl.java
  src/main/java/com/umc/ttt/domain/mail/service/MailService.java
  src/main/java/com/umc/ttt/domain/mail/service/MailServiceImpl.java
  src/main/java/com/umc/ttt/domain/member/handler/MemberHandler.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandService.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/com/umc/ttt/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/BookClubHandler.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/BookLetterBookHandler.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/BookLetterCategoryHandler.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/EMailHandler.java
  src/main/java/com/umc/ttt/global/apiPayload/exception/handler/ReviewHandler.java
Labels: :sparkles: feature, :recycle: refactor

#113 [fix #58] 에러 핸들러 변경 : 중복 이메일 요청 불가
  src/main/java/com/umc/ttt/global/oauth2/service/GoogleIdTokenVerify.java
Labels: :memo: docs, :recycle: refactor

#115 [refactor #112] 책 추천 검색어 조회 API 리팩토링
  src/main/java/com/umc/ttt/domain/book/repository/BookRepository.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/bookLetter/repository/BookLetterBookRepository.java
  src/main/java/com/umc/ttt/domain/bookLetter/repository/BookLetterRepository.java
Labels: :recycle: refactor

#118 [fix #114] 홈화면-리마인드(서평 가져오기)에서 사용자 서평만 보이도록 오류 수정
  src/main/java/com/umc/ttt/domain/home/converter/HomeConverter.java
  src/main/java/com/umc/ttt/domain/home/dto/HomeResponseDTO.java
  src/main/java/com/umc/ttt/domain/home/service/HomeServiceImpl.java
  src/main/java/com/umc/ttt/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandService.java
  src/main/java/com/umc/ttt/domain/review/service/ReviewCommandServiceImpl.java
Labels: :recycle: refactor

#120 [fix #117] 사용자가 가입한 북클럽의 서평 목록만 조회되도록 수정
  src/main/java/com/umc/ttt/domain/bookClub/controller/ReadingRecordController.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/BookClubMemberRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/repository/ReadingRecordRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/service/ReadingRecordService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/ReadingRecordServiceImpl.java
Labels: :recycle: refactor

#121 [feat #119] 블라인드 북 위젯 API 구현
  src/main/java/com/umc/ttt/TttApplication.java
  src/main/java/com/umc/ttt/domain/book/controller/BookRestController.java
  src/main/java/com/umc/ttt/domain/book/converter/BookConverter.java
  src/main/java/com/umc/ttt/domain/book/dto/BookResponseDTO.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryService.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryServiceImpl.java
  src/main/java/com/umc/ttt/domain/book/service/BookScheduler.java
Labels: :sparkles: feature

#123 [refactor #122] 책 추천 검색어 조회 API 응답 데이터 수정
  src/main/java/com/umc/ttt/domain/book/controller/BookRestController.java
  src/main/java/com/umc/ttt/domain/book/converter/BookConverter.java
  src/main/java/com/umc/ttt/domain/book/dto/BookResponseDTO.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryService.java
  src/main/java/com/umc/ttt/domain/book/service/BookQueryServiceImpl.java
Labels: :recycle: refactor

#124 [fix] 공간 추천 시 null 체크 추가
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceQueryServiceImpl.java
Labels: :bug: bug

#127 [fix #126]홈화면 디버깅 코드 제거
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubQueryServiceImpl.java
Labels: :recycle: refactor

#129 [FIX #128] 홈화면-리마인드에서 책 존재하지 않는 오류 수정 & 리뷰 캘린더 보기 수정
  src/main/java/com/umc/ttt/domain/review/converter/ReviewConverter.java
  src/main/java/com/umc/ttt/domain/review/repository/ReviewRepository.java
Labels: :recycle: refactor

#130 [fix] 책마다 북클럽 참여 현황 조회 시 이번 달 이후 북클럽까지 포함
  src/main/java/com/umc/ttt/domain/bookClub/repository/BookClubRepository.java
  src/main/java/com/umc/ttt/domain/bookClub/service/BookClubServiceImpl.java
Labels: :recycle: refactor

#137 [refactor #136] 서평 인증 사진 업로드 구현
  src/main/java/com/umc/ttt/domain/bookClub/controller/ReadingRecordController.java
  src/main/java/com/umc/ttt/domain/bookClub/converter/ReadingRecordConverter.java
  src/main/java/com/umc/ttt/domain/bookClub/dto/ReadingRecordRequestDTO.java
  src/main/java/com/umc/ttt/domain/bookClub/service/ReadingRecordService.java
  src/main/java/com/umc/ttt/domain/bookClub/service/ReadingRecordServiceImpl.java
Labels: :recycle: refactor

#133 [refactor #132] 책 이미지 변경
  src/main/java/com/umc/ttt/domain/book/controller/BookRestController.java
  src/main/java/com/umc/ttt/domain/book/dto/BookFetchDTO.java
  src/main/java/com/umc/ttt/domain/book/entity/Book.java
  src/main/java/com/umc/ttt/domain/book/service/BookCommandService.java
  src/main/java/com/umc/ttt/domain/book/service/BookCommandServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#139 [refactor] 에디터 픽 공간 변경
  src/main/java/com/umc/ttt/domain/place/service/impl/PlaceQueryServiceImpl.java
Labels: :recycle: refactor
